name: Frontend CI

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test  

    - name: Send email on success
    # Send email only if previous steps were successful
      if: success()  
      uses: dawidd6/action-send-mail@v3.8.0
      with:
        files: README.html  
        subject: Build was successful and GitHub actions are properly working :D 

      # Define environment variables for SMTP configuration
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN}}
        TO_EMAIL: ${{ secrets.MAIL_TO }}
        FROM_EMAIL: ${{ secrets.MAIL_FROM }}
        SMTP_HOST: smtp.hobbes.cse.buffalo.edu
        SMTP_PORT: 589
        SMTP_SECURE: tls
