name: Frontend Test CI

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16  # Use Node.js version 16
    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build  # Assuming this script generates files in the "build" directory

    - name: Run built files
      run: |
        if [ $exit_status -ne 0 ]; then
          echo "Error: Build or execution failed"
          cat error.log
          exit 1  # This line ensures the workflow exits with an error status
        fi
    
    - name: Send email on success or failure
      uses: dawidd6/action-send-mail@v3.8.0
      with:
        from: cse370-hci-social-apps@buffalo.edu
        body: error.log  # Attach the error log file
        subject: Build failed :(

      # Define environment variables for SMTP configuration
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        TO_EMAIL: ${{ secrets.MAIL_TO }}
        FROM_EMAIL: ${{ secrets.MAIL_FROM }}
        SMTP_HOST: smtp.hobbes.cse.buffalo.edu
        SMTP_PORT: 589
        SMTP_SECURE: tls
